const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
  console.error(`[set-env] .env file not found at ${envPath}`);
  process.exit(1);
}

const envVars = {};
fs.readFileSync(envPath, 'utf8')
  .split(/\r?\n/)
  .forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq === -1) return;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    envVars[key] = value;
  });

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];
const missing = required.filter((k) => !envVars[k]);
if (missing.length) {
  console.error(`[set-env] Missing env vars in .env: ${missing.join(', ')}`);
  process.exit(1);
}

const buildFile = (production) => `// AUTO-GENERATED by scripts/set-env.js — do not edit by hand.
export const environment = {
  production: ${production},
  firebase: {
    apiKey: ${JSON.stringify(envVars.FIREBASE_API_KEY)},
    authDomain: ${JSON.stringify(envVars.FIREBASE_AUTH_DOMAIN)},
    projectId: ${JSON.stringify(envVars.FIREBASE_PROJECT_ID)},
    storageBucket: ${JSON.stringify(envVars.FIREBASE_STORAGE_BUCKET)},
    messagingSenderId: ${JSON.stringify(envVars.FIREBASE_MESSAGING_SENDER_ID)},
    appId: ${JSON.stringify(envVars.FIREBASE_APP_ID)},
    measurementId: ${JSON.stringify(envVars.FIREBASE_MEASUREMENT_ID || '')},
  },
};
`;

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.writeFileSync(path.join(envDir, 'environment.ts'), buildFile(true));
fs.writeFileSync(path.join(envDir, 'environment.development.ts'), buildFile(false));

console.log('[set-env] Environment files generated successfully.');
